[package]
name = "occasion-android"
version = "0.1.0"
edition = "2024"

[dependencies]
jni = "0.21.1"
occasion = "0.3.0"
serde = "1.0.219"
serde_json = "1.0.142"

[lib]
crate-type = ["dylib"]
name = "occasion_android"
